export const data = JSON.parse({
  "id": 191,
  "date": "2020-07-21",
  "org_pers_information": "Universitat Politècnica de València",
  "manifestation_name": "L'arbre del Tirant",
  "country": "ES",
  "city": "12",
  "city_name_aux": "Gandia",
  "latitude_longitude": "38.96422811116893,-0.1775362719055229",
  "manifestation_description": "The sculptor Ramón de Soto, created this work at the request of the Gandia City Council in 1990 to commemorate the five centuries since the publication of the novel \"Tirant lo Blanch\" by Joanot Martorell. The figure of red metallic tubes suggests in an abstract way a medieval knight on a horse next to a large tree, in total it measures 20 meters high. The monument that was not understood and had an unpopular reception after its first installation was removed. The history of this sculpture has been very eventful, because after being removed from its original place, it was abandoned for more than 10 years, being later rebuilt by Joan Sapena. In September 2012 it suffered the consequences of the tornado that devastated the fair that was mounted at that time and the statue itself, for which a second restoration took place years later. Today it is located in the same enclosure with the restored area enhancing the figure of heritage due to the nature that surrounds it.",
  "image": "ec5ce74602dc2326e6107e25814382923abd915d1595323954.jpeg",
  "time": "N/A",
  "manifestation_type": "I",
  "manifestation_actors": "Ayuntamiento de Gandia",
  "photos": "1",
  "audios": null,
  "videos": null,
  "maps": null,
  "bibliography": null,
  "other": null,
  "email": "tomaslobatobrotons@gmail.com",
  "id_user": 191,
  "search": "Gandía",
  "protected_no": "no",
  "protected_yes": "0",
  "protected_unesco": "",
  "protected_others": "",
  "protected_description": "",
  "comments": "Ramón de Soto created this work as a request of the Gandia City Council in 1990 to commemorate the five centuries of the publication of the novel \"Tirant lo Blanch\" by Joanot Martorell. It represents a knight in a horse towards a big tree.",
  "proposal": "0",
  "verified": "1",
  "links_interest": "[{\"url\":\"\"}]",
  "unesco_items": "[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]",
  "unesco_items_intangible": "[\"\",\"\",\"\",\"\",\"\"]",
  "tags": "",
  "subtype_two": 0,
  "image_author": "Tomás Lobato Brotons",
  "manifestation_short_description_local": "Ramón de Soto creó este trabajo a petición del Ayuntamiento de Gandia en 1990 para conmemorar los cinco siglos de la publicación de la novela \"Tirant lo Blanch\" de Joanot Martorell. Representa a un caballero en un caballo hacia un gran árbol.",
  "manifestation_description_local": "El escultor Ramón de Soto, creó esta obra por petición del Ayuntamiento de Gandia en 1990 para conmemorar los cinco siglos de la publicación de la novela “Tirant lo Blanch” de Joanot Martorell. La figura de tubos metálicos rojos sugiere de forma abstracta a un caballero medieval en un caballo junto a un gran árbol, en total mide 20 metros de alto. El monumento que no fue comprendido y tuvo una acogida impopular tras su primera instalación se quitó. La historia de esta escultura ha sido muy accidentada, pues tras ser retirada de su lugar original, estuvo abandonada durante más de 10 años, siendo posteriormente reconstruída por Joan Sapena. En septiembre de 2012 sufrió las consecuencias del tornado que asoló la feria que en esas fechas estaba montada y la propia estatua, por lo que tuvo lugar una segunda restauración años después. Hoy en día se encuentra en el mismo recinto con la zona restaurada realzando la figura del patrimonio debido a la naturaleza que la rodea. ",
  "creation_date": "2021-02-01"
})